[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[context.production]
  environment = { NODE_VERSION = "18.x" }

[context.production.environment]
  REACT_APP_API_URL = "https://api.velvetcoin.com"

[context.staging.environment]
  REACT_APP_API_URL = "https://staging-api.velvetcoin.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"