[build]
  command = "npm run build"
  publish = "build"
  # Removed the functions directory as it's not used
  # functions = "netlify/functions"

# Removed the [context.production] section that sets NODE_VERSION

[context.production.environment]
  REACT_APP_API_URL = "https://velvetcoin-mernstack-d9c8d5423380.herokuapp.com/"

[context.staging.environment]
  REACT_APP_API_URL = "https://velvetcoin-mernstack-d9c8d5423380.herokuapp.com/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
